# Classification

*In the third week of class, we will look at classification...*

So far, we have looked at making predictions in which the outcome is a continous value. Today, we will look at **classification**, in which our outcome is a categorical value. We first start with binary classification, in which there is only two possible outcomes, usually defined by `True` or `False` values. However, for many classification models, they predict the *probability* of whether an event happens or not, on a continuous scale from 0 to 1. Then, given the predicted probability, we say after a threshold, we classify the outcome as `True` or `False` values.

Using the same data as before, we define someone is at risk for $Hypertension$ if their diastolic pressure is greater than 80 or their systolic pressure is greater than 130. Our goal is to classify whether someone is at high risk for $Hypertension$.

Let's look at the distribution of Hypertension vs. No Hypertension:

```{python}
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from formulaic import model_matrix
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

nhanes = pd.read_csv("classroom_data/NHANES.csv")
nhanes.drop_duplicates(inplace=True)
nhanes['Hypertension'] = (nhanes['BPDiaAve'] > 80) | (nhanes['BPSysAve'] > 130)

nhanes['Hypertension2'] = nhanes['Hypertension'].replace({True: "Hypertension", False: "No Hypertension"})

plt.clf()
plt.hist(nhanes['Hypertension2'])
plt.show()

```

We see that there is a lot more data for the No Hypertension group (88%) compared Hypertension group (22%), so this could be a potential **class imbalance** in our modeling. We will revisit the consequence of class imbalance later today.

We then split our data in training and testing, as usual:

```{python}
#train test
nhanes_train, nhanes_test = train_test_split(nhanes, test_size=0.2, random_state=42)
```

Then, we start looking at possible predictors that may be associated with our binary response. Let's consider $BMI$ as a candidate predictor:

```{python}
plt.clf()
ax = sns.boxplot(y="Hypertension2", x="BMI", data=nhanes_train)
ax.set_ylabel('')
plt.show()
```

Great, there seems to be an association. However, recall that our classification model is going to be *making predictions of probabilit*y on a continuous scale of 0 to 1 before we classify it into two categories. Therefore, it makes sense to examine the relationship between BMI and empirical Hypertension probability in our data exploration. To do so, we will need to *bin* our data by small chunks of BMI values and calculate the empirical Hypertension probability for that bin. We plot the midpoint binned BMI value vs. empirical Hypertension probability for 20 bins:

```{python}
nhanes_train['bins'] = pd.cut(nhanes_train['BMI'], bins=20) 


nhanes_train_binned = nhanes_train.groupby('bins')['Hypertension'].agg(['sum', 'count']).reset_index()
nhanes_train_binned['p'] = nhanes_train_binned['sum'] / nhanes_train_binned['count']
 
nhanes_train_binned['log_odds'] = np.log(nhanes_train_binned['p'] / (1 - nhanes_train_binned['p']))
nhanes_train_binned['bin_midpoint'] = nhanes_train_binned['bins'].apply(lambda x: x.mid)

nhanes_train_binned = nhanes_train_binned.replace([np.inf, -np.inf], np.nan)
nhanes_train_binned = nhanes_train_binned.dropna()

#predictor vs probability
plt.clf()
plt.scatter(nhanes_train_binned['bin_midpoint'], nhanes_train_binned['p'], color='blue')
plt.xlabel('BMI - Binned Midpoint')
plt.ylabel('Empirical Hypertension Probability')
plt.ylim(0, 1)
plt.grid(True)
plt.show()

```

Great, looks like we have a relationship, but it doesn't encompass the full spectrum of probabilities.

## Logistic Regression

Now, let's build the model $P(Hypertension) = f(BMI)$ to make a prediction of $Hyptertension$ given $BMI$. Notice that the left hand side of the equation is the *probability* of having $Hypertension$, indicated by the $P()$ function.

### Logistic Transformation

Our usual Linear Regression model $P(Hypertension)=\beta_0+\beta_1 \cdot BMI$ *does not* give us outputs between 0 and 1. To deal with this, we perform the **Logistic Transformation:**

$$P(Hyptertension) = \frac{1}{1+e^{-(\beta_0 + \beta_1 \cdot BMI)}}$$

Therefore, the relationship between the X and Y axis is not going to be a straight line, but rather a non-linear, "S-shaped" one. Let's fit this model and look at the model visually to understand.

```{python}
y_train, X_train = model_matrix("Hypertension ~ BMI", nhanes_train)
logit_model = LogisticRegression().fit(X_train, y_train)

plt.clf()
plt.scatter(X_train.BMI, logit_model.predict_proba(X_train)[:, 1], color="red", label="Fitted Line")
plt.scatter(nhanes_train_binned['bin_midpoint'], nhanes_train_binned['p'], color='blue')


plt.xlabel('BMI')
plt.ylabel('Probability of Hypertension')
plt.ylim(0, 1)
plt.legend()
plt.show()
```

This shows that the logistic model was able to model some of the relationship between $BMI$ and $P(Hypertension)$, but the model predicts much higher $P(Hypertension)$ at high values of $BMI$.

It is hard to figure out visually when the data can fall on a logistic S-curve - one can imagine a red line stretched out more, etc. If we move the equation around so that the right hand side is linear:

$$log(\frac{P(Hyptertension)}{1 - P(Hyptertension)}) = \beta_0 + \beta_1 \cdot BMI$$

The left hand side of the equation is called the **Log-Odds**. A Log-Odds of 0 indicate a 50:50 probability, positive values indicate a higher than 50% probability, and negative values indicate a lower than 50% probability.

```{python}
plt.clf()
p = logit_model.predict_proba(X_train)[:, 1]
log_odds = np.log(p / (1 - p))
plt.scatter(X_train.BMI, log_odds, color="red", label="Fitted Line")
plt.scatter(nhanes_train_binned['bin_midpoint'], nhanes_train_binned['log_odds'], color='blue')
plt.xlabel('BMI')
plt.ylabel('Log Odds of Hypertension')
plt.legend()
plt.show()
```

Now we see why exactly our logistic regression model was limited to fit the relationship between predictor and response, as we have reformulated the problem closer to a linear regression problem. We could improve the model by using polynomial terms. We will revisit this later.

### Model Evaluation

Remember that we still need to get from probability to classification. We will set a reasonable, interpretable cutoff of 50%: if the probability of having Hypertension is \>=50%, then classify that person having Hypertension. Otherwise, they do not have Hypertension This cutoff called the **Decision Boundary**.

As an aside, we can also evaluate the model based on just the probability it predicted, and it actually contains more information than if we had set our decision boundary to make it a classifier. However, these metrics of evaluation, namely [**Cross Entropy** and **Brier Scores**](https://aml4td.org/chapters/cls-metrics.html#sec-cls-metrics-soft), are harder to interpret, and are less commonly reported in biomedical research.

Given this decision boundary, let's examine evaluate the model on the test set, and look at its accuracy rate:

```{python}
y_test, X_test = model_matrix("Hypertension ~ BMI", nhanes_test)

print('Accuracy = ', accuracy_score(y_test, logit_model.predict(X_test))) 
```

Okay, that's a starting point!

However, we need to be mindful of the class imbalance we saw in the dataset at the beginning of the lesson. Recall we roughly have 88% of our data as No Hypertension. If we have a classifier that *always* predicted No Hypertension, then we achieve a 88% accuracy rate, but this model is not particularly novel and it raises questions of whether our model of 76% accuracy is novel.

We can break down classification accuracy to four additional results, via a table called the **Confusion Matrix**:

```{python}
cm = confusion_matrix(y_test, logit_model.predict(X_test))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["No Hypertension", "Hyptertension"])
disp.plot()
plt.show()
```

The top left hand corner is the number of True Negatives (1128), the top right hand corner is the number of False Positives (24), the bottom left corner is the number of False Negatives (325), and the bottom right corner is the number of True Positives (15).

Our **Sensitivity** (accuracy of Hypertension events) is defined as: $\frac{TP}{TP+FN}$, which is 15/(15+325) = 4%

Our **Specificity** (accuracy of No Hypertension events) is defined as: $\frac{TN}{TN+FP}$, which is 1128/(1128+24) = 98%.

Therefore, we do a pretty terrible job of predicting the Hypertension cases!

What happened exactly? Let's look back at the Training Data: it seems that from the plots that we are making predictions of Hypertension for BMI of 50 or more. However, there are so few people with such a high BMI that even if most of those folks have Hypertension, the model missed most of the folks with Hypertension in the 20-40 BMI range. This range wasn't high enough for our decision boundary of 50% probability, so we missed out most of our Hypertension people.

What can we do? We can change the decision boundary to be lower, which will improve our sensitivity at the expense of our specificity, and vice versa if we change the decision boundary to be higher. What if we set the new decision boundary to be .2?

```{python}

new_pred = [1 if x >= .2 else 0 for x in logit_model.predict_proba(X_test)[:, 1]]

cm = confusion_matrix(y_test, new_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["No Hypertension", "Hyptertension"])
disp.plot()
plt.show()
```

## Assumptions of logistic regression

### Linearity of log odds - predictor relationship

We can rewrite $P(Hyptertension) = \frac{e^{\beta_0 + \beta_1X}}{1+e^{\beta_0 + \beta_1X}}$ as $log(\frac{P(Hyptertension)}{1 - P(Hyptertension)}) = \beta_0 + \beta_1 \cdot BMI$

where the left hand side is called the **log odds** or the **logit**.

```{python}

```

Deviance: https://stackoverflow.com/questions/50975774/calculate-residual-deviance-from-scikit-learn-logistic-regression-model

### Predictors are not colinear

covered last week

### No outliers

covered last week

### Number of predictors is less than the number of samples

covered last week

### interactions: H-statistic?

## Appendix: Inference for Logistic Regression

Let's do the same for our Logic Regression Classifier model, which has an equation of:

$$
\frac{p(Hypertension)}{1-p(Hypertension)}=e^{\beta_0 + \beta_1 \cdot BMI}
$$

On the left hand side of the equationis the **Odds** of having Hypertension.

$\beta_0$ is a parameter describing \_\_, and $\beta_1$ is a parameter describing \_\_\_

```{python}
import statsmodels.api as sm

logit_model = sm.Logit(y_train, X_train).fit()

logit_model.summary()
```

## Appendix: ROC Curve

```{python}

from sklearn.metrics import RocCurveDisplay
from sklearn.metrics import roc_curve, roc_auc_score

# Compute ROC curve
fpr, tpr, thresholds = roc_curve(y_test, logit_model.predict(X_test), drop_intermediate=False)

display = RocCurveDisplay.from_predictions(y_test, logit_model.predict(X_test))
plt.show()
```
